from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def __init__(self):
        self.pushButton = None

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.widget = QtWidgets.QWidget(MainWindow)
        self.widget.setObjectName("widget")
        self.Paciente = QtWidgets.QTabWidget(self.widget)
        self.Paciente.setGeometry(QtCore.QRect(10, 40, 561, 281))
        self.Paciente.setObjectName("Paciente")
        self.widget1 = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.widget1.setFont(font)
        self.widget1.setObjectName("widget1")
        self.comboBox_2 = QtWidgets.QComboBox(self.widget1)
        self.comboBox_2.setGeometry(QtCore.QRect(40, 20, 171, 25))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(3, "")
        self.pushButton = QtWidgets.QPushButton(self.widget1)
        self.pushButton.setGeometry(QtCore.QRect(360, 100, 88, 25))
        self.pushButton.setObjectName("pushButton")
        self.Paciente.addTab(self.widget1, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_4.setGeometry(QtCore.QRect(0, 20, 221, 25))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(2, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(3, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(4, "")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit.setGeometry(QtCore.QRect(310, 20, 113, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 100, 88, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.Paciente.addTab(self.tab_4, "")
        self.widget2 = QtWidgets.QWidget()
        self.widget2.setObjectName("widget2")
        self.comboBox = QtWidgets.QComboBox(self.widget2)
        self.comboBox.setGeometry(QtCore.QRect(20, 20, 141, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget2)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 90, 88, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.Paciente.addTab(self.widget2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_3.setGeometry(QtCore.QRect(10, 20, 211, 25))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_3)
        self.pushButton_4.setGeometry(QtCore.QRect(360, 90, 88, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.Paciente.addTab(self.tab_3, "")
        self.widget3 = QtWidgets.QWidget()
        self.widget3.setObjectName("widget3")
        self.comboBox_6 = QtWidgets.QComboBox(self.widget3)
        self.comboBox_6.setGeometry(QtCore.QRect(110, 20, 211, 25))
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget3)
        self.pushButton_5.setGeometry(QtCore.QRect(410, 200, 88, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label = QtWidgets.QLabel(self.widget3)
        self.label.setGeometry(QtCore.QRect(20, 30, 66, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget3)
        self.label_2.setGeometry(QtCore.QRect(5, 80, 91, 20))
        self.label_2.setObjectName("label_2")
        self.comboBox_5 = QtWidgets.QComboBox(self.widget3)
        self.comboBox_5.setGeometry(QtCore.QRect(110, 70, 121, 25))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_3 = QtWidgets.QLabel(self.widget3)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 66, 17))
        self.label_3.setObjectName("label_3")
        self.comboBox_7 = QtWidgets.QComboBox(self.widget3)
        self.comboBox_7.setGeometry(QtCore.QRect(110, 120, 86, 25))
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.label_4 = QtWidgets.QLabel(self.widget3)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 161, 16))
        self.label_4.setObjectName("label_4")
        self.comboBox_8 = QtWidgets.QComboBox(self.widget3)
        self.comboBox_8.setGeometry(QtCore.QRect(210, 170, 86, 25))
        self.comboBox_8.setObjectName("comboBox_8")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.comboBox_8.addItem("")
        self.Paciente.addTab(self.widget3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 20, 141, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab)
        self.pushButton_7.setGeometry(QtCore.QRect(390, 210, 88, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab)
        self.pushButton_13.setGeometry(QtCore.QRect(240, 160, 88, 25))
        self.pushButton_13.setObjectName("pushButton_13")
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab)
        self.textEdit_2.setGeometry(QtCore.QRect(160, 60, 281, 70))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(30, 90, 111, 20))
        self.label_5.setObjectName("label_5")
        self.Paciente.addTab(self.tab, "")
        self.widget4 = QtWidgets.QWidget()
        self.widget4.setObjectName("widget4")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget4)
        self.pushButton_8.setGeometry(QtCore.QRect(20, 20, 141, 25))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget4)
        self.pushButton_9.setGeometry(QtCore.QRect(410, 210, 88, 25))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget4)
        self.pushButton_12.setGeometry(QtCore.QRect(260, 150, 88, 25))
        self.pushButton_12.setObjectName("pushButton_12")
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget4)
        self.textEdit_3.setGeometry(QtCore.QRect(180, 60, 291, 70))
        self.textEdit_3.setObjectName("textEdit_3")
        self.label_6 = QtWidgets.QLabel(self.widget4)
        self.label_6.setGeometry(QtCore.QRect(20, 80, 111, 17))
        self.label_6.setObjectName("label_6")
        self.Paciente.addTab(self.widget4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.textEdit = QtWidgets.QTextEdit(self.tab_2)
        self.textEdit.setGeometry(QtCore.QRect(30, 10, 411, 70))
        self.textEdit.setObjectName("textEdit")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_10.setGeometry(QtCore.QRect(257, 190, 171, 25))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_11.setGeometry(QtCore.QRect(67, 100, 141, 25))
        self.pushButton_11.setObjectName("pushButton_11")
        self.Paciente.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.widget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.Paciente.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Paciente.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Hospital Centenario"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Hospital Provincial"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Heca"))
        self.pushButton.setText(_translate("MainWindow", "Continuar"))
        self.Paciente.setTabText(self.Paciente.indexOf(self.widget1), _translate("MainWindow", "Efector"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Nombre y Apellido"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Matricula"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "\"Ingrese su nombre completo aqui\""))
        self.pushButton_2.setText(_translate("MainWindow", "Continuar"))
        self.Paciente.setTabText(self.Paciente.indexOf(self.tab_4), _translate("MainWindow", "Médico Solicitante"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Paciente Nuevo"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Paciente en Tratamiento"))
        self.pushButton_3.setText(_translate("MainWindow", "Continuar"))
        self.Paciente.setTabText(self.Paciente.indexOf(self.widget2), _translate("MainWindow", "Paciente"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Primera vez"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Renovación de tratamiento"))
        self.pushButton_4.setText(_translate("MainWindow", "Continuar"))
        self.Paciente.setTabText(self.Paciente.indexOf(self.tab_3), _translate("MainWindow", "Solicitud"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "Paracetamol"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "Ibuprofeno"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "Enalapril"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "Calcio"))
        self.pushButton_5.setText(_translate("MainWindow", "Continuar"))
        self.label.setText(_translate("MainWindow", "Droga"))
        self.label_2.setText(_translate("MainWindow", "Presentación"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Comprimidos"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "Ampollas"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "Capsulas"))
        self.label_3.setText(_translate("MainWindow", "Dosis"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "1gr"))
        self.comboBox_7.setItemText(1, _translate("MainWindow", "500ml"))
        self.comboBox_7.setItemText(2, _translate("MainWindow", "25ml"))
        self.comboBox_7.setItemText(3, _translate("MainWindow", ".50gr"))
        self.label_4.setText(_translate("MainWindow", "Tiempo de Tratamiento"))
        self.comboBox_8.setItemText(0, _translate("MainWindow", "1 mes"))
        self.comboBox_8.setItemText(1, _translate("MainWindow", "2 meses"))
        self.comboBox_8.setItemText(2, _translate("MainWindow", "3 meses"))
        self.comboBox_8.setItemText(3, _translate("MainWindow", "4 meses"))
        self.Paciente.setTabText(self.Paciente.indexOf(self.widget3), _translate("MainWindow", "Tratamiento"))
        self.pushButton_6.setText(_translate("MainWindow", "Adjuntar Archivo"))
        self.pushButton_7.setText(_translate("MainWindow", "Continuar"))
        self.pushButton_13.setText(_translate("MainWindow", "Guardar"))
        self.label_5.setText(_translate("MainWindow", "Observaciones"))
        self.Paciente.setTabText(self.Paciente.indexOf(self.tab), _translate("MainWindow", "Resumen Historia Clinica"))
        self.pushButton_8.setText(_translate("MainWindow", "Adjuntar Archivo"))
        self.pushButton_9.setText(_translate("MainWindow", "Continuar"))
        self.pushButton_12.setText(_translate("MainWindow", "Guardar"))
        self.label_6.setText(_translate("MainWindow", "Observaciones"))
        self.Paciente.setTabText(self.Paciente.indexOf(self.widget4), _translate("MainWindow", "Laboratorio"))
        self.pushButton_10.setText(_translate("MainWindow", "Solicitar y Terminar "))
        self.pushButton_11.setText(_translate("MainWindow", "Guardar comentario"))
        self.Paciente.setTabText(self.Paciente.indexOf(self.tab_2), _translate("MainWindow", "Justificación de Pedido"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
